apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homer-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homer-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
