apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homer-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homer-operator.labels" . | nindent 4 }}
data:
  base_config.yml: |-
{{ .Values.baseConfig | indent 4 }}
