apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homer-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homer-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "homer-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homer-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "homer-operator.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.operator.enabled }}
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.operatorImage.repository }}:{{ .Values.operatorImage.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.operatorImage.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared
              mountPath: /www/assets/
            - name: config
              mountPath: /www/assets/base_config.yml
              subPath: base_config.yml
            - name: config
              mountPath: /www/assets/extra.css
              subPath: extra.css
        {{- end }}
        - name: homer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /www/default-assets/* /www/assets/"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.operator.enabled }}
            - name: shared
              mountPath: /www/assets/
            - name: config
              mountPath: /www/assets/extra.css
              subPath: extra.css
            {{- else }}
            - name: config
              mountPath: /www/assets/config.yml
              subPath: base_config.yml
            - name: config
              mountPath: /www/assets/extra.css
              subPath: extra.css
            {{- end }}
      volumes:
        {{- if .Values.operator.enabled }}
        - name: shared
          emptyDir: {}
        {{- end }}
        - name: config
          configMap:
            name: {{ include "homer-operator.fullname" . }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
