apiVersion: v1
kind: Service
metadata:
  name: {{ include "homer-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homer-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "homer-operator.selectorLabels" . | nindent 4 }}
